import UserProfile from './UserProfile';
import SignUp from './auth/SignUp';
import Login from './auth/Login';
import Doctors from './Doctors';
import Home from './Home';
import Menu from './Menu';
import DailyInsights from './DailyInsights';
import Article from './Article';
import Explore from './Explore';
import ExploreArticle from './ExploreArticle';
export { Home, SignUp, Login, UserProfile, Doctors, Menu, DailyInsights, Article, Explore, ExploreArticle };
